### ISSUE TITLE
warning on install 

### ISSUE THREAD

**Issue by marcosrjjunior** [acro5piano/kysely-migration-cli#12]
### Description

I'm receiving a warning message during the dependency installation, that is probably related to [this PR](https://github.com/acro5piano/kysely-migration-cli/pull/11).

We could probably fix this by updating the `commander` dependency to ^11.0.0.

### Screenshot
<img width="534" alt="Screenshot 2023-10-03 at 9 15 22 am" src="https://github.com/acro5piano/kysely-migration-cli/assets/5287262/a9724be3-8c08-468d-a377-c2308ecf9ece">

**Comment by acro5piano** [comment]
Fixed on https://github.com/acro5piano/kysely-migration-cli/releases/tag/v0.2.3
