### ISSUE TITLE
Ability to customize the template/written migration files

### ISSUE THREAD

**Issue by zandzpider** [acro5piano/kysely-migration-cli#14]
It would be really neat if we could customize the file that is generated!

**Comment by acro5piano** [comment]
Thanks for your interest. That would be an interesting feature. If you create a pull request, I'm happy to merge it!

**Comment by marcosrjjunior** [comment]
PR up

**Comment by acro5piano** [comment]
Implemented in v0.3.0. Thank you @marcosrjjunior
