### ISSUE TITLE
Suggestion: Use `import type { Kysely }` for migration template

### ISSUE THREAD

**Issue by lockinmarv** [acro5piano/kysely-migration-cli#15]
Hey! 

What do you think about using the explicit type import for `Kysely` in migration files?

Instead of
`import { Kysely } from 'kysely'`

it would be
`import type { Kysely } from 'kysely'`

**Comment by acro5piano** [comment]
@m4rvr That would be nice. Can you make a pull request? Thanks

**Comment by acro5piano** [comment]
Fixed on v0.3.0

**Comment by lockinmarv** [comment]
Damn, sorry @acro5piano. Totally forgot about that 🙃 
Thanks @marcosrjjunior for doing it! 🙏
