### ISSUE TITLE
Suggestion: Fix doc to save-dev and not save

### ISSUE THREAD

**Issue by fokolo** [acro5piano/kysely-migration-cli#17]
Hi :) 
As far as I understand this library is only for dev work therefore it should not be bundled in any production build no?

so in the doc instead of:

> Installation
> `npm install --save kysely-migration-cli`
> If you prefer Yarn:
> `yarn add kysely-migration-cli`

it should be
> Installation
> `npm install --save kysely-migration-cli`
> If you prefer Yarn:
> `yarn add kysely-migration-cli`
> pnpm:
> `pnpm i -D kysely-migration-cli`

Good job at the lightweight lib!

**Comment by acro5piano** [comment]
@fokolo Thank you for your interest in this project and the suggestion. I think it's up to users; some users want to install it as a production dependency to run migration to production DB, while others want to run them in a separate environment such as CI. I want to make the default unopionated, so the current doc sounds good.

Besides, your suggestion to include `pnpm` in the doc is great - if you create a PR for this, I'm happy to merge it.

**Comment by marcosrjjunior** [comment]
yes, sometimes you want to perform this script on a production env.

A good example of that is when migrating latest changes on your automated deployment.

**Comment by acro5piano** [comment]
Closing as dev/non-dev policy is now clear and pnpm was added to readme.
