### ISSUE TITLE
[suggestion] moving repo to kysely-org

### ISSUE THREAD

**Issue by marcosrjjunior** [acro5piano/kysely-migration-cli#23]
hey @acro5piano 

we were discussing on kysely channel, the possibility of moving this repo to the organisation and so we could start a **kysely-cli**, that could potentially be extended/improved to include other scripts.
Having a repo inside the organisation has many benefits, including more support and trust.

initially we would have the migration script and run something like:
```bash
kysely migration up | down | ...
```

[channel discussion](https://discord.com/channels/890118421587578920/1073949928453328897/1230847474885853184)

would you be interested on this migration?

**Comment by acro5piano** [comment]
Hi @marcosrjjunior, thank you for your suggestion! I've read the related chat on Discord and I'm glad to hear that this repository is somewhat useful to Kysely community.

I'm truly positive to move this repository under the official org. Here are some thoughts though:

- **The command-line interface**. This library does not provide a command interface respecting Kysely's intention not to confuse TypeScript users. So your suggestion might differ from the following philosophy:

> This is because Kysely's migrations are also written in TypeScript. To run the migrations, you need to first build the TypeScript code into JavaScript. A CLI would cause confusion over which migrations are being run, the TypeScript ones or the JavaScript ones

I'm not sure whether we should provide the command interface or not. However, as you might know this library has experimental support of the command interface, so if Kysely team suggests it I'm totally agree to it.

- **License**. I want to keep my name in README and LICENSE as a OSS developer.
