### ISSUE TITLE
[v0.4.1] Cannot find module 'kysely-migration-cli'

### ISSUE THREAD

**Issue by marcosrjjunior** [acro5piano/kysely-migration-cli#27]
I'm having issues to install the dependency after the latest update v0.4.1.

<img width="452" alt="Screenshot 2024-06-24 at 3 07 32 PM" src="https://github.com/acro5piano/kysely-migration-cli/assets/5287262/c7235647-aae4-46d5-ada0-a21f4adfb49b">

have you cleared your dist dir before publishing to npm?

to reproduce you can just start a new project and add the dependency using `pnpm add kysely-migration-cli`, vscode should also complain.

**Comment by acro5piano** [comment]
Let me check this...

**Comment by acro5piano** [comment]
Thank you @marcosrjjunior , it was fixed in v0.4.2. If you have any troubles after updating, please let me know.
